### ISSUE TITLE
translate6frames.sh: command not found

### ISSUE THREAD

**Issue by Siacm** [Gardner-BinfLab/invasive_salmonella#1]
Hi - this bash script translate6frames.sh is missing from the fastq_pipeline.

**Comment by nwheeler443** [comment]
Hi! This script should be contained in the bbmap package, as specified as a dependency in the Wiki

**Comment by Siacm** [comment]
Thanks for the reply! Ah - I found it. I hadn't included it in my ./bashrc file path. Thanks!
