### ISSUE TITLE
RE: Interpreting results

### ISSUE THREAD

**Issue by Siacm** [Gardner-BinfLab/invasive_salmonella#2]
Hi! I think I've successfully ran the run_invasiveness_index bash script, I think the final output is the votelog file? But I'm not sure how to interpret the results.

**Comment by nwheeler443** [comment]
Hi! Yes, the votelog file records the proportion of trees in the random forest that vote for an invasive phenotype. This can be used to compare scores across related isolates, as in Figure 6 of this paper: https://www.nature.com/articles/s41467-019-11844-z

**Comment by Siacm** [comment]
Hi Nicole! Thank you for the reply. I see! So based on the score distribution of isolates, the tool enables you to determine the score threshold for an invasive phenotype?

**Comment by Siacm** [comment]
Also, is there an option to run on assembled contigs?

**Comment by nwheeler443** [comment]
I would think of invasiveness as less of a binary trait and more of a continuum that isolates can move across - the invasiveness index can measure movement along the continuum toward being more adapted to invasive infection. 

I do have a pipeline for running the analysis on assemblies - I will add it to the Github today

**Comment by Siacm** [comment]
I see - this makes sense. Regarding your paper - I may have missed this, but did any of the phenotypes you used to validate the invasive model mention where the isolate was isolated from (i.e blood, urine)? Thanks again!

That would be great. Thank you.

**Comment by Siacm** [comment]
Great. Thanks Nicole for all your help and the assembly pipeline.
