### ISSUE TITLE
Running build_rf.Rmd

### ISSUE THREAD

**Issue by Aravindphoenix** [Gardner-BinfLab/invasive_salmonella#4]
I am new to R. I do not how to change values in build_rf.Rmd and run my data. Can you guide me how to run build_rf.Rmd?

**Comment by nwheeler443** [comment]
Hi there, sorry for the late reply. Have you seen the [section in the Wiki ](https://github.com/Gardner-BinfLab/invasive_salmonella/wiki/Building-your-own-model) on getting your data ready for build_rf.Rmd?
